services:
  app:
    build: .
    # image: rental:latest
    container_name: rental
    restart: always
    environment:
      - SECRET_KEY=AAAAAAAAAAAAAAAAAAAAAAAA
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_NAME=araba_kiralama
      - DB_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network
  db:
    image: mysql:8.0
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Rp123456
      MYSQL_DATABASE: araba_kiralama
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
    - mysql-data:/var/lib/mysql
    networks:
      - app-network
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    environment:
      DOMAIN_NAME: techprodevops.com
    depends_on:
      - app
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
    name: rental
volumes:
  mysql-data: